name: nips_papers_LDA
dependencies:
- beautiful-soup=4.3.2=py27_0
- certifi=14.05.14=py27_0
- decorator=4.0.2=py27_0
- gensim=0.10.3=np19py27_0
- ipykernel=4.0.3=py27_0
- ipython=4.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.0.0=py27_0
- jupyter_core=4.0.4=py27_0
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- mistune=0.7.1=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.0=py27_0
- nltk=3.0.4=np19py27_0
- notebook=4.0.4=py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py27_0
- path.py=7.6=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- ptyprocess=0.4=py27_0
- pygments=2.0.2=py27_0
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.4=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_0
- readline=6.2=2
- scipy=0.16.0=np19py27_1
- setuptools=18.1=py27_0
- simplegeneric=0.8.1=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.2.1=py27_0
- traitlets=4.0.0=py27_0
- wheel=0.24.0=py27_0
- yaml=0.1.6=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.3.2
  - disco==0.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.0.0
  - jupyter-core==4.0.4
  - lda==1.0.2
  - pbr==0.11.0
  - stop-words==2015.2.23.1
